config/routes.rb
Rails.application.routes.draw do
  root to: 'haikus#daily_challenge'
  resources :haikus
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/haiku.rb
class Haiku < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :haikus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  before_action :set_haiku, only: [:show, :edit, :update, :destroy]

  # GET /haikus
  # GET /haikus.json
  def index
    @haikus = Haiku.all
  end

  # GET /haikus/1
  # GET /haikus/1.json
  def show
  end

  # GET /haikus/new
  def new
    @haiku = Haiku.new
  end

  # GET /haikus/1/edit
  def edit
  end

  # POST /haikus
  # POST /haikus.json
  def create
    @haiku = Haiku.new(haiku_params)

    respond_to do |format|
      if @haiku.save
        format.html { redirect_to @haiku, notice: 'Haiku was successfully created.' }
        format.json { render :show, status: :created, location: @haiku }
      else
        format.html { render :new }
        format.json { render json: @haiku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /haikus/1
  # PATCH/PUT /haikus/1.json
  def update
    respond_to do |format|
      if @haiku.update(haiku_params)
        format.html { redirect_to @haiku, notice: 'Haiku was successfully updated.' }
        format.json { render :show, status: :ok, location: @haiku }
      else
        format.html { render :edit }
        format.json { render json: @haiku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /haikus/1
  # DELETE /haikus/1.json
  def destroy
    @haiku.destroy
    respond_to do |format|
      format.html { redirect_to haikus_url, notice: 'Haiku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def daily_challenge
    @haikus = Haiku.all
    render layout: "application_index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_haiku
      @haiku = Haiku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def haiku_params
      params.require(:haiku).permit(:user_id, :kamigo, :nakashichi, :shimogo, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :email, :avater, :age, :sex, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/haikus/_form.html.erb
<%= form_with(model: haiku, local: true) do |form| %>
  <% if haiku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(haiku.errors.count, "error") %> prohibited this haiku from being saved:</h2>

      <ul>
      <% haiku.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, id: :haiku_user_id, value: 1 %>

  <div class="field">
    <dl class="cf">
      <dt><%= form.label :kamigo %>:</dt>
      <dd><%= form.text_field :kamigo, id: :haiku_kamigo %></dd>
    </dl>
  </div>

  <div class="field">
    <dl class="cf">
      <dt><%= form.label :nakashichi %>:</dt>
      <dd><%= form.text_field :nakashichi, id: :haiku_nakashichi %></dd>
    </dl>
  </div>

  <div class="field">
    <dl class="cf">
      <dt><%= form.label :shimogo %>:</dt>
      <dd><%= form.text_field :shimogo, id: :haiku_shimogo %></dd>
    </dl>
  </div>

  <div class="haiku_new_post_right_description field">
    <dl class="cf">
      <dt><%= form.label :description %></dt>
      <dd><%= form.text_area :description, id: :haiku_description %></dd>
    </dl>
  </div>

  <div class="form_submit actions">
    <ul class="form_submit_settings">
      <li><label><input type="checkbox"> 自由律として投稿する</label></li>
      <li><label><input type="checkbox"> 投稿の前に文字数のチェックをする</label></li>
      <li><label><input type="checkbox"> 投稿の前に季語の有無のチェックをする</label></li>
      <li><label><input type="checkbox"> 投稿の前にプレゼンテーションを表示する</label></li>
    </ul>
    <p class="banners form_submit_banners"><%= image_tag("banner_example.jpg") %></p>
    <%= form.submit %>
  </div>
<% end %>

app/views/haikus/daily_challenge.html.erb
<div id="index">
  <div class="daily_challenge" style="background-image:url(/assets/bg_sakura.jpg)">
    <p>デイリーチャレンジ</p>
    <p>桜の木を見上げる女性で一句</p>
    <p>
      <%= link_to new_haiku_path, {class: "daily_challenge_try_button"} do %>
        <%= image_tag("icon_light.svg") %>
        <span>デイリーチャレンジに挑戦</span>
      <% end %>
    </p>
  </div>

  <div class="index_menu_list cf">
    <ul class="cf">
      <li><%= link_to haikus_path do %><%= image_tag("icon_my_haiku.png") %><p>わたしの句</p><% end %></li>
      <li><a href="javascript:void(0);"><%= image_tag("icon_heart.svg") %><p>お気に入り</p></a></li>
      <li><a href="javascript:void(0);"><%= image_tag("icon_circle.png") %><p>フレンド</p></a></li>
      <li><a href="javascript:void(0);"><%= image_tag("icon_circle.png") %><p>サークル</p></a></li>
    </ul>
    <div><%= link_to new_haiku_path do %><%= image_tag("icon_pencil.svg") %><p>投稿</p><% end %></div>
  </div>

  <div class="index_my_profile cf">
    <div class="index_my_profile_left"  style="background-image:url(/assets/image_my_profile.jpg)">
      <%= image_tag("image_my_profile.jpg") %>
    </div>
    <div class="index_my_profile_right">
      <div><span>みならい俳人</span><h2>ゆうな</h2></div>
      <ul class="cf">
        <li><%= link_to user_path(1) do %><%= image_tag("icon_fukidashi"); %>プロフィール確認</a><% end %></li>
        <li><%= link_to edit_user_path(1) do %><%= image_tag("icon_scissors"); %>プロフィール編集</a><% end %></li>
        <li><a href="javascript:void(0);"><%= image_tag("icon_setting"); %>環境設定</a></li>
      </ul>
    </div>
  </div>

  <div class="index_haikus">
    <div class="index_haikus_in">
      <ul class="index_haikus_tab cf">
        <li><a href="javascript:void(0);">全部</a></li>
        <li><a href="javascript:void(0);">フレンド</a></li>
        <li><a href="javascript:void(0);">サークル</a></li>
      </ul>
      <ul class="index_haikus_list cf">
        <% @haikus.each_with_index do |haiku, count| %>
          <li class="cf">
            <p class="index_haiku_photo"><%= image_tag("bg_sakura") %></p>
            <p class="index_haiku_main">
              <span><%= haiku.kamigo %></span><br />
              <span><%= haiku.nakashichi %></span><br />
              <span><%= haiku.shimogo %></span><br />
              <span><%= image_tag("icon_loupe") %><%= link_to "この句の詳細へ >", haiku_path(haiku) %></span>
            </p>
            <p class="index_haiku_user"><%= haiku.user.nickname %></p>
          </li>
          <% break if count >= 10 %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/haikus/edit.html.erb
<h1>Editing Haiku</h1>

<%= render 'form', haiku: @haiku %>

<%= link_to 'Show', @haiku %> |
<%= link_to 'Back', haikus_path %>

app/views/haikus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Haikus</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Kamigo</th>
      <th>Nakashichi</th>
      <th>Shimogo</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @haikus.each do |haiku| %>
      <tr>
        <td><%= haiku.user_id %></td>
        <td><%= haiku.kamigo %></td>
        <td><%= haiku.nakashichi %></td>
        <td><%= haiku.shimogo %></td>
        <td><%= haiku.description %></td>
        <td><%= link_to 'Show', haiku %></td>
        <td><%= link_to 'Edit', edit_haiku_path(haiku) %></td>
        <td><%= link_to 'Destroy', haiku, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Haiku', new_haiku_path %>

app/views/haikus/new.html.erb
<div class="haiku_new">
  <div class="haiku_new_post cf">
  <div class="haiku_new_post_left">
    <h1>本日のお題に挑戦</h1>
    <div class="haiku_new_post_left_image">
      <%= image_tag("bg_sakura.jpg") %>
    </div>
  </div>
  <div class="haiku_new_post_right">
    <%= render 'form', haiku: @haiku %>
  </div>
  <div class="menu_buttons">
    <%= link_to '投稿お題一覧に戻る', haikus_path, class: "button_all" %>
  </div>
</div>

app/views/haikus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @haiku.user_id %>
</p>

<p>
  <strong>Kamigo:</strong>
  <%= @haiku.kamigo %>
</p>

<p>
  <strong>Nakashichi:</strong>
  <%= @haiku.nakashichi %>
</p>

<p>
  <strong>Shimogo:</strong>
  <%= @haiku.shimogo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @haiku.description %>
</p>

<%= link_to 'Edit', edit_haiku_path(@haiku) %> |
<%= link_to 'Back', haikus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hinemosu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hinemosu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <div id="container">
        <div id="header" class="cf">
          <div class="header_left"><p class="header_icon_frame"><%= image_tag("icon_menu.svg") %></p></div>
          <div class="header_center"><%= image_tag("logo.svg") %></div>
          <div class="header_right"><p class="header_icon_frame"><%= image_tag("icon_pencil.svg") %></p></div>
        </div>
        <div id="index_contents">
          <%= yield %>
        </div>
        <div id="footer"></div>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :user_nickname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :avater %>
    <%= form.text_field :avater, id: :user_avater %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :user_age %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.number_field :sex, id: :user_sex %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :user_birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Email</th>
      <th>Avater</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.email %></td>
        <td><%= user.avater %></td>
        <td><%= user.age %></td>
        <td><%= user.sex %></td>
        <td><%= user.birthday %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Avater:</strong>
  <%= @user.avater %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>